services:
  frontend:
    image: vm0077/aquathon_app:frontend
    build:
      context: aquathon_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mern
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: '0.0.0.0:4000'
      NEXT_PUBLIC_WS_BASE_URL: '0.0.0.0:4000'
  backend:
    image: vm0077/aquathon_app:backend
    build:
      context: aquathon_backend
      dockerfile: Dockerfile
    networks:
      - mern
    ports:
      - "4000:4000"
    restart: always
networks:
  mern:
    driver: bridge

