version: '3.8'

services:
  frontend:
    depends_on:
      - backend
    image: vm0077/aquathon_app:frontend
    build:
      context: aquathon_frontend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mern
    restart: always
    environment:
      NEXT_PUBLIC_API_BASE_URL: 'http://localhost:4000/api'
      NEXT_PUBLIC_WS_BASE_URL: 'http://localhost:4000'
    volumes:
      - ./aquathon_frontend/src:/app/src
      - ./aquathon_frontend/public:/app/public

  backend:
    depends_on:
      - mongodb
    image: vm0077/aquathon_app:backend
    build:
      context: aquathon_backend
      dockerfile: Dockerfile
    networks:
      - mern
    ports:
      - "4000:4000"
    environment:
      - NODE_MONGODB=mongodb://root:example@mongodb:27017/test?authSource=admin
      - NODE_PORT=4000
    restart: always
    volumes:
      - ./aquathon_backend/.:/app
  mongodb:
    image: mongo
    restart: always
    command: mongod --logpath=/dev/null --auth
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mern

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    networks:
      - mern
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodbdata:
    driver: local

networks:
  mern:
    driver: bridge
