name: Deploy Aquathon

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build Docker Frontend Image
          run: docker build -t vm0077/aquathon_app:frontend ./aquathon_frontend
        - name: Push Docker Frontend Image
          run: docker push vm0077/aquathon_app:frontend
        - name: Build Docker Backend Image
          run: docker build -t vm0077/aquathon_app:backend ./aquathon_backend
        - name: Push Docker Backend Image
          run: docker push vm0077/aquathon_app:backend
          with:
            node-version: 20

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pill Image from docker hub
        run: docker pull vm0077/aquathon_app:frontend
      - name: Pill Image from docker hub
        run: docker pull vm0077/aquathon_app:backend
      - name: Run Docker Container Compose
        run: docker compose up -d